FROM bash
LABEL NAME="NGSmain" Version="1.0"
LABEL author="Samuel Soukup"
LABEL contact="soukup.sam(at)gmail.com"

RUN mkdir /DockerBuildInfo
COPY Dockerfile /DockerBuildInfo

COPY README.md /README.md

CMD ["/bin/bash"]
